### ISSUE TITLE
missing -key when calling older versions of Crypt::CBC

### ISSUE THREAD

**Issue by lwaggonerExpedia** [rlauer6/perl-amazon-s3#11]
https://github.com/rlauer6/perl-amazon-s3/blob/624f4d055693a18c87562a345f75b5c89e284b13/src/main/perl/lib/Amazon/S3.pm.in#L198

First thing I tried to do with this module hit the issue where -key wasn't passed here. I see on https://github.com/rlauer6/perl-amazon-s3/blob/624f4d055693a18c87562a345f75b5c89e284b13/src/main/perl/lib/Amazon/S3.pm.in#L181 it is. 

My assumption is both -pass and -key should be provided (one of those is probably backwards compatible?) - Should a fix be put here too? Not sure if something on my system is old or code needs an update?

**Comment by rlauer6** [comment]
The newer version of Crypt::CBC uses `pass` not `key` but will accept either.  I will provide a patch, but if you upgrade your Crypt:::CBC you should be good.
