### ISSUE TITLE
Missing dependency on `Crypt::CBC` and `Crypt::Blowfish`

### ISSUE THREAD

**Issue by depressed-pho** [rlauer6/perl-amazon-s3#12]
This module uses `Crypt::CBC` and `Crypt::Blowfish`:
https://github.com/rlauer6/perl-amazon-s3/blob/master/src/main/perl/lib/Amazon/S3.pm.in#L167

But they aren't listed as dependencies:
https://github.com/rlauer6/perl-amazon-s3/blob/master/cpan/requires

**Comment by rlauer6** [comment]
I believe the intent of the eval around the require was to prevent `$encryption_key` from being set.  If there is no encryption key then no attempt is made to encrypt or decrypt.  Does this produce an error for you?

**Comment by depressed-pho** [comment]
Let me restate the problem. `Amazon::S3` uses `Crypt::CBC` and `Crypt::Blowfish` but its [META.json](https://metacpan.org/release/BIGFOOT/Amazon-S3-0.63/source/META.json) does not have them listed in its `/prereqs/runtime/requires`. This causes package managers to miss the fact that these two modules are in fact required to actually use `Amazon::S3`.

**Comment by depressed-pho** [comment]
Understood. Thank you for your explanation. I thought those `require`s were for loading modules lazily but I was wrong about it.
